#!/usr/bin/env bash
# 用途: context-map.sh の `cm_generate` 経路の AC カバレッジを fixture ベースで検証する
#       （Task 1 の `_Requirements_partial: 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.9, 2.10,
#       NFR 2.1, NFR 2.3_` で deferred された behavioral regression test を集約する）。
# 配置先: docs/specs/313-feat-watcher-context-map-per-task-agent/test-fixtures/test-cm-generate.sh
# 依存: bash 4+, awk / grep / wc。modules/context-map.sh を source して直接呼ぶ。
# セットアップ参照先: docs/specs/313-feat-watcher-context-map-per-task-agent/impl-notes.md
#
# Usage:
#   bash docs/specs/313-feat-watcher-context-map-per-task-agent/test-fixtures/test-cm-generate.sh
#
# Exit code:
#   0 = すべての assert が pass
#   1 = いずれかの assert が fail（標準エラーにどれが失敗したか出力）

# SC2030 / SC2031 (info): 本ファイル中の env 改変はすべて意図的にサブシェル内で完結させて
# 親シェルへ漏洩させない設計（各 case を独立して評価するため）。shellcheck の警告は
# false-positive として info レベルで抑止する。
# shellcheck disable=SC2030,SC2031

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
FIXTURE_DIR="$SCRIPT_DIR"
# repo root はこの fixture dir から 4 階層上（test-fixtures/<spec>/specs/docs/<root>）。
REPO_ROOT=$(cd "$SCRIPT_DIR/../../../.." && pwd)
MODULE="$REPO_ROOT/local-watcher/bin/modules/context-map.sh"

if [ ! -f "$MODULE" ]; then
  echo "[FATAL] module not found: $MODULE" >&2
  exit 1
fi

# cm_log/cm_warn が参照するグローバル。
export REPO="owner/test-313"

# shellcheck source=/dev/null
source "$MODULE"

fail_count=0
pass_count=0

# ── ヘルパ: 期待される文字列が含まれることを assert ──
assert_contains() {
  # $1 = label, $2 = haystack file, $3 = needle (literal substring, grep -F)
  local label="$1" file="$2" needle="$3"
  if grep -qF -- "$needle" "$file"; then
    echo "[OK]   $label"
    pass_count=$((pass_count + 1))
  else
    echo "[FAIL] $label: '$needle' not found in $file" >&2
    fail_count=$((fail_count + 1))
  fi
}

assert_eq() {
  # $1 = label, $2 = actual, $3 = expected
  local label="$1" actual="$2" expected="$3"
  if [ "$actual" = "$expected" ]; then
    echo "[OK]   $label"
    pass_count=$((pass_count + 1))
  else
    echo "[FAIL] $label: actual=[$actual] expected=[$expected]" >&2
    fail_count=$((fail_count + 1))
  fi
}

# spec dir を準備し fixture を配置するヘルパ。$1 = task_id（tasks.md の対象 task）。
# 戻り値: tmp dir のパスを stdout に。
make_spec_tmp() {
  local task_id="$1"
  local tmp
  tmp=$(mktemp -d)
  mkdir -p "$tmp/spec"
  cp "$FIXTURE_DIR/tasks-sample.md" "$tmp/spec/tasks.md"
  cp "$FIXTURE_DIR/design-sample.md" "$tmp/spec/design.md"
  printf '%s' "$tmp"
  : "$task_id"  # quiet unused-warning placeholder（呼び出し側で利用）
}

# ── Case 1: cm_generate が context-map.md を生成し全 AC セクションを含むこと ──
# Req 2.2 (Task ID/Name) / 2.3 (Boundary) / 2.4 (Candidate files) /
# 2.5 (Candidate tests) / 2.6 (Candidate docs) / 2.7 (Search constraints)
case1_tmp=$(make_spec_tmp "1")
(
  export PER_TASK_LOOP_ENABLED=true
  export CONTEXT_MAP_ENABLED=true
  REPO_DIR="$case1_tmp" SPEC_DIR_REL=spec cm_generate "1" >/dev/null
)
case1_map="$case1_tmp/spec/context-map.md"
if [ ! -f "$case1_map" ]; then
  echo "[FAIL] case1: context-map.md was not generated at $case1_map" >&2
  fail_count=$((fail_count + 1))
else
  assert_contains "case1 Req 2.2 Task section"        "$case1_map" "## Task"
  assert_contains "case1 Req 2.2 Task ID"             "$case1_map" "- ID: 1"
  assert_contains "case1 Req 2.2 Task Name"           "$case1_map" "context-map モジュールを追加する"
  assert_contains "case1 Req 2.3 Boundary section"    "$case1_map" "## Boundary (from tasks.md"
  # Req 2.3 補助: `_Boundary:_` の抽出ロジック自体が boundary CSV を返すことを直接検証する
  # （cm_compose の bullet 展開には既知の latent issue があり「確認事項」で報告する）。
  boundary_csv=$(cm_resolve_boundary "$case1_tmp/spec/tasks.md" "1")
  assert_eq "case1 Req 2.3 cm_resolve_boundary CSV" "$boundary_csv" "context-map.sh"
  assert_contains "case1 Req 2.4 Candidate files"     "$case1_map" "## Candidate files"
  # Req 2.4: candidate files セクションに boundary token が解決した結果 1 件以上が出ること
  case1_files_section=$(awk '/^## Candidate files/{f=1;next} /^## /{f=0} f' "$case1_map")
  if echo "$case1_files_section" | grep -q "context-map.sh"; then
    echo "[OK]   case1 Req 2.4 Candidate files lists boundary-derived path"
    pass_count=$((pass_count + 1))
  else
    echo "[FAIL] case1 Req 2.4 Candidate files section did not list boundary-derived path" >&2
    fail_count=$((fail_count + 1))
  fi
  assert_contains "case1 Req 2.5 Candidate tests"     "$case1_map" "## Candidate tests"
  assert_contains "case1 Req 2.6 Candidate docs"      "$case1_map" "## Candidate docs"
  assert_contains "case1 Req 2.6 docs lists tasks.md" "$case1_map" "- tasks.md"
  assert_contains "case1 Req 2.7 Search constraints"  "$case1_map" "## Search constraints"
  assert_contains "case1 Req 2.7 READ FIRST"          "$case1_map" "READ FIRST:"
  assert_contains "case1 deterministic banner"        "$case1_map" "generated by context-map.sh"
fi

# ── Case 2: NFR 2.1 冪等性 — 同一 (tasks.md, design.md, task_id) 入力で output が byte 一致 ──
# 「同一入力」とは spec dir 内容が同一の状態を指すため、別々の fresh temp dir に同じ fixture を
# 配置して 2 回独立に cm_generate を呼び、両 output の byte 一致を確認する。
case2a_tmp=$(make_spec_tmp "1")
case2b_tmp=$(make_spec_tmp "1")
(
  export PER_TASK_LOOP_ENABLED=true
  export CONTEXT_MAP_ENABLED=true
  REPO_DIR="$case2a_tmp" SPEC_DIR_REL=spec cm_generate "1" >/dev/null
  REPO_DIR="$case2b_tmp" SPEC_DIR_REL=spec cm_generate "1" >/dev/null
)
case2_first=$(cat "$case2a_tmp/spec/context-map.md" 2>/dev/null || true)
case2_second=$(cat "$case2b_tmp/spec/context-map.md" 2>/dev/null || true)
assert_eq "case2 NFR 2.1 idempotency (byte-equal across fresh runs)" "$case2_second" "$case2_first"
rm -rf "$case1_tmp" "$case2a_tmp" "$case2b_tmp"

# ── Case 3: Req 2.9 — `_Boundary:_` 不在 task で「解決不能」明示 ──
# Task 3 は fixture の tasks-sample.md で `_Boundary:_` を持たない。
case3_tmp=$(make_spec_tmp "3")
(
  export PER_TASK_LOOP_ENABLED=true
  export CONTEXT_MAP_ENABLED=true
  REPO_DIR="$case3_tmp" SPEC_DIR_REL=spec cm_generate "3" >/dev/null
)
case3_map="$case3_tmp/spec/context-map.md"
if [ ! -f "$case3_map" ]; then
  echo "[FAIL] case3: context-map.md was not generated at $case3_map" >&2
  fail_count=$((fail_count + 1))
else
  assert_contains "case3 Req 2.9 unresolved marker"        "$case3_map" "(resolution: none"
  assert_contains "case3 Req 2.9 still has Boundary heading" "$case3_map" "## Boundary"
fi
rm -rf "$case3_tmp"

# ── Case 4: Req 2.10 / NFR 4.1 — 200 行 / 8 KB 上限超過で truncate marker 末尾追記 ──
# 巨大 context-map.md を直接配置し、cm_truncate_if_oversize を直接適用する。
case4_tmp=$(mktemp -d)
mkdir -p "$case4_tmp/spec"
big_map="$case4_tmp/spec/context-map.md"
# 300 行（200 行を確実に超える）+ 各行を十分長くして 8 KB も超過させる。
{
  for i in $(seq 1 300); do
    printf 'line-%03d: %s\n' "$i" "$(printf '=%.0s' {1..40})"
  done
} > "$big_map"
big_orig_lines=$(wc -l < "$big_map" | tr -d '[:space:]')
big_orig_bytes=$(wc -c < "$big_map" | tr -d '[:space:]')
cm_truncate_if_oversize "$big_map"
new_lines=$(wc -l < "$big_map" | tr -d '[:space:]')
# 200 行（cap）+ truncate marker 用 1 行（空行は marker の前 / 同じ）= 202 行以内に収まる想定。
if [ "$new_lines" -gt 202 ] || [ "$new_lines" -lt 201 ]; then
  echo "[FAIL] case4 Req 2.10 truncated line count out of range: $new_lines (expected 201..202)" >&2
  fail_count=$((fail_count + 1))
else
  echo "[OK]   case4 Req 2.10 truncated line count = $new_lines"
  pass_count=$((pass_count + 1))
fi
assert_contains "case4 Req 2.10 truncate marker"     "$big_map" "truncated by cm_truncate_if_oversize"
assert_contains "case4 Req 2.10 marker shows orig N" "$big_map" "$big_orig_lines lines"
assert_contains "case4 Req 2.10 marker shows orig M" "$big_map" "$big_orig_bytes bytes"
rm -rf "$case4_tmp"

# ── Case 5: NFR 2.3 — 生成失敗を仕込んでも rc=0 で抜ける ──
# 5.a: SPEC_DIR_REL 未解決（dir 不在）でも rc=0
case5a_tmp=$(mktemp -d)
set +e
(
  export PER_TASK_LOOP_ENABLED=true
  export CONTEXT_MAP_ENABLED=true
  REPO_DIR="$case5a_tmp" SPEC_DIR_REL=does-not-exist cm_generate "1" 2>/dev/null
)
rc_5a=$?
set -e
assert_eq "case5a NFR 2.3 missing spec dir → rc=0" "$rc_5a" "0"
rm -rf "$case5a_tmp"

# 5.b: tasks.md / design.md 不在でも rc=0 で抜け、context-map.md は「解決不能」明示で生成される
case5b_tmp=$(mktemp -d)
mkdir -p "$case5b_tmp/spec"
set +e
(
  export PER_TASK_LOOP_ENABLED=true
  export CONTEXT_MAP_ENABLED=true
  REPO_DIR="$case5b_tmp" SPEC_DIR_REL=spec cm_generate "1" 2>/dev/null
)
rc_5b=$?
set -e
assert_eq "case5b NFR 2.3 missing tasks/design → rc=0" "$rc_5b" "0"
# 入力ファイル不在でも cm_compose は最小 context-map.md を出力する（Req 2.9 + NFR 2.3）。
if [ -f "$case5b_tmp/spec/context-map.md" ]; then
  assert_contains "case5b NFR 2.3 fallback content" "$case5b_tmp/spec/context-map.md" "(resolution: none"
fi
rm -rf "$case5b_tmp"

# 5.c: 空 task_id 引数でも rc=0 で抜ける
set +e
(
  export PER_TASK_LOOP_ENABLED=true
  export CONTEXT_MAP_ENABLED=true
  REPO_DIR=/tmp SPEC_DIR_REL=spec cm_generate "" 2>/dev/null
)
rc_5c=$?
set -e
assert_eq "case5c NFR 2.3 empty task_id → rc=0" "$rc_5c" "0"

# ── 結果サマリ ──
echo "---"
echo "PASS: $pass_count / FAIL: $fail_count"
if [ "$fail_count" -gt 0 ]; then
  exit 1
fi
exit 0
